### ISSUE TITLE
Configuration is an dummy file

### ISSUE THREAD

**Issue by hasezoey** [jellyfin/jellyfin-plugin-coverartarchive#11]
affected file: https://github.com/jellyfin/jellyfin-plugin-coverartarchive/blob/master/Jellyfin.Plugin.CoverArtArchive/Configuration/configPage.html

it only contains example configuration, no explanation and probably the options do nothing

**Comment by oddstr13** [comment]
Can confirm that I was lazy and just left the template config page in.
Should be fixed with next plugin release.
